[package]
name = "opensoft-open-profiler"
version = "0.1.4"
description = "A full LLM profile manager"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "opensoft_open_profiler_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5", features = [] }

[dependencies]
opensoft-open-profiler-core = { path = "../crates/open-profiler-core" }
serde.workspace = true
tauri = { version = "2.10", features = [] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
  "Win32_Foundation",
  "Win32_System_Diagnostics_ToolHelp",
  "Win32_System_Threading",
  "Win32_UI_WindowsAndMessaging",
] }
